user_token: ZGQxMWJlMzUtOTc0My00NDMyLTllOWEtODhhZjdlNDliYzA4XzQ3NTE=

session:
  key: CaY5iCkYtN7DqXdiYK1BvmGrQuaSA4Tl4bEk9my0jc0=
admin:
  email: admin@admin.com
  password: admin
bot:
  token: vk1.a.i0CPUsFYoSFt20rKSxTJMEjSSRgvv8BhKZyoz7J7TPTNGyrehkeULHVFuP9u1UlvOYsHafThshWi3aS3Xw98A_s1M59Gk_iowEHE5sU-E4VFfEcBBJWzl7HsxVb6dfI46YD2dq7bdCh83nlIUNlvVOr9hRIlkwZwJad3wJ7zbBUbXwhL4HMDZqj2gCLsymT-0waLPqecItfWjU3xXB21LA
  group_id: 218883569


